name: AI Deployment to Server

on:
  push:
    branches: [ ai ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Connecting to server
      uses: appleboy/chosen@master
      with:
        host: ${{ secrets.www.dixie-net.com }}
        username: ${{ secrets.rickyplambert57 }}
        key: ${{ secrets.JAMES_LAMBERT }}
        port: ${{ secrets.192.168.1.251}}
        script: |
          ./update_mygemini_web_react.sh
        


